# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Photopop(object):
    def setupUi(self, Photopop):
        Photopop.setObjectName("Photopop")
        Photopop.resize(1000, 800)
        Photopop.setStyleSheet("background:black;\n"
"color:white;")
        self.centralwidget = QtWidgets.QWidget(Photopop)
        self.centralwidget.setObjectName("centralwidget")
        self.file = QtWidgets.QPushButton(self.centralwidget)
        self.file.setGeometry(QtCore.QRect(20, 10, 261, 51))
        self.file.setStyleSheet("border:3px dashed #ffffff;\n"
"border-radius: 12px;\n"
"font-size:20px;\n"
"font-weight:500;")
        self.file.setObjectName("file")
        self.listpictures = QtWidgets.QListWidget(self.centralwidget)
        self.listpictures.setGeometry(QtCore.QRect(20, 90, 261, 651))
        self.listpictures.setStyleSheet("border:3px solid #ffffff;\n"
"border-radius: 12px;\n"
"font-size:20px;\n"
"font-weight:500;")
        self.listpictures.setObjectName("listpictures")
        self.pictures = QtWidgets.QLabel(self.centralwidget)
        self.pictures.setGeometry(QtCore.QRect(300, 20, 681, 611))
        self.pictures.setStyleSheet("border:3px dotted #ffffff;\n"
"border-radius: 12px;\n"
"font-size:20px;\n"
"font-weight:500;")
        self.pictures.setObjectName("pictures")
        self.left = QtWidgets.QPushButton(self.centralwidget)
        self.left.setGeometry(QtCore.QRect(290, 680, 131, 51))
        self.left.setStyleSheet("border:3px dashed #ffffff;\n"
"border-radius: 10px;\n"
"font-size:20px;\n"
"font-weight:500;")
        self.left.setObjectName("left")
        self.right = QtWidgets.QPushButton(self.centralwidget)
        self.right.setGeometry(QtCore.QRect(430, 680, 131, 51))
        self.right.setStyleSheet("border:3px dashed #ffffff;\n"
"border-radius: 10px;\n"
"font-size:20px;\n"
"font-weight:500;")
        self.right.setObjectName("right")
        self.mirror = QtWidgets.QPushButton(self.centralwidget)
        self.mirror.setGeometry(QtCore.QRect(570, 680, 131, 51))
        self.mirror.setStyleSheet("border:3px dashed #ffffff;\n"
"border-radius: 10px;\n"
"font-size:20px;\n"
"font-weight:500;")
        self.mirror.setObjectName("mirror")
        self.sharpness = QtWidgets.QPushButton(self.centralwidget)
        self.sharpness.setGeometry(QtCore.QRect(710, 680, 131, 51))
        self.sharpness.setStyleSheet("border:3px dashed #ffffff;\n"
"border-radius: 10px;\n"
"font-size:20px;\n"
"font-weight:500;")
        self.sharpness.setObjectName("sharpness")
        self.b_w = QtWidgets.QPushButton(self.centralwidget)
        self.b_w.setGeometry(QtCore.QRect(850, 680, 131, 51))
        self.b_w.setStyleSheet("border:3px dashed #ffffff;\n"
"border-radius: 10px;\n"
"font-size:20px;\n"
"font-weight:500;")
        self.b_w.setObjectName("b_w")
        Photopop.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Photopop)
        self.statusbar.setObjectName("statusbar")
        Photopop.setStatusBar(self.statusbar)

        self.retranslateUi(Photopop)
        QtCore.QMetaObject.connectSlotsByName(Photopop)

    def retranslateUi(self, Photopop):
        _translate = QtCore.QCoreApplication.translate
        Photopop.setWindowTitle(_translate("Photopop", "Photopop"))
        self.file.setText(_translate("Photopop", "File"))
        self.pictures.setText(_translate("Photopop", "Picture"))
        self.left.setText(_translate("Photopop", "Left"))
        self.right.setText(_translate("Photopop", "Right"))
        self.mirror.setText(_translate("Photopop", "Mirror"))
        self.sharpness.setText(_translate("Photopop", "Sharpness"))
        self.b_w.setText(_translate("Photopop", "Black/White"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Photopop = QtWidgets.QMainWindow()
    ui = Ui_Photopop()
    ui.setupUi(Photopop)
    Photopop.show()
    sys.exit(app.exec_())
